# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Markdrop < Formula
  desc "Peer-to-peer file sharing from the terminal via WebRTC"
  homepage "https://markdrop.in"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/himanshkukreja/markdrop/releases/download/v0.1.0/markdrop_0.1.0_darwin_amd64.tar.gz"
      sha256 "ebad096571b3a31faeea357ff240e899268b68f067d5b8ef0cefaafa5c78b5a7"

      define_method(:install) do
        bin.install "markdrop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/himanshkukreja/markdrop/releases/download/v0.1.0/markdrop_0.1.0_darwin_arm64.tar.gz"
      sha256 "d96fa2d196a1fb1ec8779daaa19591888939066b6d7d9a650e9e5de249655175"

      define_method(:install) do
        bin.install "markdrop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/himanshkukreja/markdrop/releases/download/v0.1.0/markdrop_0.1.0_linux_amd64.tar.gz"
      sha256 "a329d93995d8e6cb3bbb1c7706b309ba6016f97ca751d9caded0d3383195f2c7"
      define_method(:install) do
        bin.install "markdrop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/himanshkukreja/markdrop/releases/download/v0.1.0/markdrop_0.1.0_linux_arm64.tar.gz"
      sha256 "b49812f51c4773f8ed93d49e122e23785e52726e3b9bb0c64368612ec6c93920"
      define_method(:install) do
        bin.install "markdrop"
      end
    end
  end

  test do
    system "#{bin}/markdrop --version"
  end
end
