# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Markdrop < Formula
  desc "Peer-to-peer file sharing from the terminal via WebRTC"
  homepage "https://markdrop.in"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/himanshkukreja/markdrop/releases/download/v0.2.0/markdrop_0.2.0_darwin_amd64.tar.gz"
      sha256 "fb72acd60f25f4a2c65ce0dff73fd07dfd322059917e353957ed062692b0f7cb"

      define_method(:install) do
        bin.install "markdrop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/himanshkukreja/markdrop/releases/download/v0.2.0/markdrop_0.2.0_darwin_arm64.tar.gz"
      sha256 "2a75731dbcab2a89b1e09f131d4a525a7482a821b65e8c457e7eaaf2d357c3fb"

      define_method(:install) do
        bin.install "markdrop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/himanshkukreja/markdrop/releases/download/v0.2.0/markdrop_0.2.0_linux_amd64.tar.gz"
      sha256 "21320ae6a8ce4bdf9191552773c9d061255d74e40aec0ea2ebe62af1c5d0f2da"
      define_method(:install) do
        bin.install "markdrop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/himanshkukreja/markdrop/releases/download/v0.2.0/markdrop_0.2.0_linux_arm64.tar.gz"
      sha256 "658b3dddcd37df952d9bdd77c2245fe0ae33fd7acc36b2446e67628b1c0ca0d6"
      define_method(:install) do
        bin.install "markdrop"
      end
    end
  end

  test do
    system "#{bin}/markdrop --version"
  end
end
